version: '3'

services:
  auth-server:
    # build: .
    image: auth_server:v1
    ports:
      - 1323:1323
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test1234
      POSTGRES_DB: auth_server

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
